---
service: sample-kamal

image: ygoto3/sample-kamal

servers:
  - sample-kamal

registry:
  username: ygoto3
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: app

builder:
  dockerfile: "../Dockerfile"
  context: ".."

healthcheck:
  path: /ok
  port: 3000

