service: sample-kamal-web

image: ygoto3/sample-kamal-web

servers:
  - 0.0.0.0

registry:
  username: ygoto3
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: app

builder:
  dockerfile: "../Dockerfile"
  context: ".."

healthcheck:
  path: /ok
  port: 80

labels:
  traefik.http.routers.sample-kamal-web-web.rule: Host(`web.example.com`)
