---

- hosts: server-ubuntu
  user: root
  tasks:

    - name: Install apt packages
      tags: packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - curl
          - docker.io
          - git

    - name: Add the app group/user
      tags: user
      block:

        - name: Add the app user
          ansible.builtin.user:
            name: app
            shell: /bin/bash
            groups: docker
            generate_ssh_key: yes
            ssh_key_bits: 2048
            ssh_key_file: .ssh/id_rsa
            append: yes

        - name: Authorize key for the app user
          ansible.builtin.copy:
            src: /home/app/.ssh/id_rsa.pub
            dest: /home/app/.ssh/authorized_keys
            remote_src: yes
            owner: app
            group: app
            mode: '0600'

        - name: Fetch key fort the app user
          ansible.builtin.fetch:
            src: /home/app/.ssh/id_rsa
            dest: ./sysroot/home/app/.ssh/
            flat: true

