---

- hosts: server-ubuntu
  user: root
  tasks:

    - name: Install apt packages
      tags: packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - curl
          - docker.io
          - git

    - name: Add the app group/user
      tags: user
      block:

        - name: Add the app user
          ansible.builtin.user:
            name: app
            shell: /bin/bash
            groups: docker
            generate_ssh_key: yes
            ssh_key_bits: 2048
            ssh_key_file: .ssh/id_rsa
            append: yes

        - name: Authorize key for the app user
          ansible.builtin.copy:
            src: /home/app/.ssh/id_rsa.pub
            dest: /home/app/.ssh/authorized_keys
            remote_src: yes
            owner: app
            group: app
            mode: '0600'

        - name: Fetch key fort the app user
          ansible.builtin.fetch:
            src: /home/app/.ssh/id_rsa
            dest: ./sysroot/home/app/.ssh/
            flat: true

    - name: Add the app group/user
      tags: firewall
      block:

      - name: Install ufw
        ansible.builtin.apt:
          name: ufw
          state: present
      
      - name: Start ufw
        ansible.builtin.systemd:
          name: ufw
          enabled: yes
          state: started

      - name: Allow ssh
        community.general.ufw:
          rule: limit
          port: ssh
          proto: tcp
      
      - name: Allow http
        community.general.ufw:
          rule: allow
          port: '80'
          proto: tcp

      - name: Allow https
        community.general.ufw:
          rule: allow
          port: '443'
          proto: tcp

      - name: Allow mysql
        community.general.ufw:
          rule: allow
          # ip range for the default docker0 interface settings 
          from: 172.17.0.0/16
          port: '3306'
          proto: tcp
 
      - name: Enable ufw
        community.general.ufw:
          state: enabled

